#ex004: Faça um programa que leia algo pelo teclado e mostre na tela o seu tipo primitivo e todas a s informações possíveis sobre ele
a = input("Digite algo: ")
print("Qual o tipo primitivo? ", type(a))
print("Só tem espaços? ", a.isspace())
print("É um número? ", a.isnumeric())
print("É alfabético? ", a.isalpha())
print("É alfanumérico? ", a.isalnum())
print("Estão em maiúsculas? ", a.isupper())
print("Estão em minúsculas? ", a.islower())
print("Está capitalizada? ", a.istitle())
